/**
 *  htmlNumberToSymbol
 * @param text - The text to be converted
 * @returns - The converted text with ACSII symbols
 */
export const htmlNumberToSymbol = (text: string) => {
    if (!text) return text;

    // Crear un mapa para búsqueda más rápida
    const entityMap = new Map<string, string>();

    // Poblar el mapa con todas las entidades
    [
        ...htmlEntityList_NCR_Hexadecimal,
        ...htmlEntityList_NCR_Decimal,
        ...htmlEntityList_NCR_Named
    ].forEach(({ html, symbol }) => {
        entityMap.set(html, symbol);
    });

    // Regexp para encontrar todas las entidades HTML
    const entityRegex = /&[^;]+;/g;

    return text
        .replaceAll('&nbsp;', ' ')
        .replace(entityRegex, (match) => entityMap.get(match) || match);
};

// Decimal NCR
// Numeric character reference (NCR) en formato decimal
const htmlEntityList_NCR_Decimal = [
    { html: '&#8226;', symbol: '•' },
    { html: '&#8211;', symbol: '–' },
    { html: '&#8212;', symbol: '—' },
    { html: '&#176;', symbol: '°' },
    { html: '&#183;', symbol: '·' },
    { html: '&#182;', symbol: '¶' },
    { html: '&#169;', symbol: '©' },
    { html: '&#8482;', symbol: '™' },
    { html: '&#174;', symbol: '®' },
    { html: '&nbsp;', symbol: ' ' },
    { html: '&#34;', symbol: '"' },
    { html: '&#38;', symbol: '&' },
    { html: '&#60;', symbol: '<' },
    { html: '&#62;', symbol: '>' },
    { html: '&#39;', symbol: "'" },
    { html: '&#0;', symbol: '' },
    { html: '&#1;', symbol: '' },
    { html: '&#2;', symbol: '' },
    { html: '&#3;', symbol: '' },
    { html: '&#4;', symbol: '' },
    { html: '&#5;', symbol: '' },
    { html: '&#6;', symbol: '' },
    { html: '&#7;', symbol: '' },
    { html: '&#8;', symbol: '' },
    { html: '&#9;', symbol: '\t' },
    { html: '&#10;', symbol: '\n' },
    { html: '&#11;', symbol: '' },
    { html: '&#12;', symbol: '' },
    { html: '&#13;', symbol: '\r' },
    { html: '&#14;', symbol: '' },
    { html: '&#15;', symbol: '' },
    { html: '&#16;', symbol: '' },
    { html: '&#17;', symbol: '' },
    { html: '&#18;', symbol: '' },
    { html: '&#19;', symbol: '' },
    { html: '&#20;', symbol: '' },
    { html: '&#21;', symbol: '' },
    { html: '&#22;', symbol: '' },
    { html: '&#23;', symbol: '' },
    { html: '&#24;', symbol: '' },
    { html: '&#25;', symbol: '' },
    { html: '&#26;', symbol: '' },
    { html: '&#27;', symbol: '' },
    { html: '&#28;', symbol: '' },
    { html: '&#29;', symbol: '' },
    { html: '&#30;', symbol: '' },
    { html: '&#31;', symbol: '' },
    { html: '&#32;', symbol: ' ' },
    { html: '&#33;', symbol: '!' },
    { html: '&#34;', symbol: '"' },
    { html: '&#35;', symbol: '#' },
    { html: '&#36;', symbol: '$' },
    { html: '&#37;', symbol: '%' },
    { html: '&#38;', symbol: '&' },
    { html: '&#39;', symbol: "'" },
    { html: '&#40;', symbol: '(' },
    { html: '&#41;', symbol: ')' },
    { html: '&#42;', symbol: '*' },
    { html: '&#43;', symbol: '+' },
    { html: '&#44;', symbol: ',' },
    { html: '&#45;', symbol: '-' },
    { html: '&#46;', symbol: '.' },
    { html: '&#47;', symbol: '/' },
    { html: '&#48;', symbol: '0' },
    { html: '&#49;', symbol: '1' },
    { html: '&#50;', symbol: '2' },
    { html: '&#51;', symbol: '3' },
    { html: '&#52;', symbol: '4' },
    { html: '&#53;', symbol: '5' },
    { html: '&#54;', symbol: '6' },
    { html: '&#55;', symbol: '7' },
    { html: '&#56;', symbol: '8' },
    { html: '&#57;', symbol: '9' },
    { html: '&#58;', symbol: ':' },
    { html: '&#59;', symbol: ';' },
    { html: '&#60;', symbol: '<' },
    { html: '&#61;', symbol: '=' },
    { html: '&#62;', symbol: '>' },
    { html: '&#63;', symbol: '?' },
    { html: '&#64;', symbol: '@' },
    { html: '&#65;', symbol: 'A' },
    { html: '&#66;', symbol: 'B' },
    { html: '&#67;', symbol: 'C' },
    { html: '&#68;', symbol: 'D' },
    { html: '&#69;', symbol: 'E' },
    { html: '&#70;', symbol: 'F' },
    { html: '&#71;', symbol: 'G' },
    { html: '&#72;', symbol: 'H' },
    { html: '&#73;', symbol: 'I' },
    { html: '&#74;', symbol: 'J' },
    { html: '&#75;', symbol: 'K' },
    { html: '&#76;', symbol: 'L' },
    { html: '&#77;', symbol: 'M' },
    { html: '&#78;', symbol: 'N' },
    { html: '&#79;', symbol: 'O' },
    { html: '&#80;', symbol: 'P' },
    { html: '&#81;', symbol: 'Q' },
    { html: '&#82;', symbol: 'R' },
    { html: '&#83;', symbol: 'S' },
    { html: '&#84;', symbol: 'T' },
    { html: '&#85;', symbol: 'U' },
    { html: '&#86;', symbol: 'V' },
    { html: '&#87;', symbol: 'W' },
    { html: '&#88;', symbol: 'X' },
    { html: '&#89;', symbol: 'Y' },
    { html: '&#90;', symbol: 'Z' },
    { html: '&#91;', symbol: '[' },
    { html: '&#92;', symbol: '\\' },
    { html: '&#93;', symbol: ']' },
    { html: '&#94;', symbol: '^' },
    { html: '&#95;', symbol: '_' },
    { html: '&#96;', symbol: '`' },
    { html: '&#97;', symbol: 'a' },
    { html: '&#98;', symbol: 'b' },
    { html: '&#99;', symbol: 'c' },
    { html: '&#100;', symbol: 'd' },
    { html: '&#101;', symbol: 'e' },
    { html: '&#102;', symbol: 'f' },
    { html: '&#103;', symbol: 'g' },
    { html: '&#104;', symbol: 'h' },
    { html: '&#105;', symbol: 'i' },
    { html: '&#106;', symbol: 'j' },
    { html: '&#107;', symbol: 'k' },
    { html: '&#108;', symbol: 'l' },
    { html: '&#109;', symbol: 'm' },
    { html: '&#110;', symbol: 'n' },
    { html: '&#111;', symbol: 'o' },
    { html: '&#112;', symbol: 'p' },
    { html: '&#113;', symbol: 'q' },
    { html: '&#114;', symbol: 'r' },
    { html: '&#115;', symbol: 's' },
    { html: '&#116;', symbol: 't' },
    { html: '&#117;', symbol: 'u' },
    { html: '&#118;', symbol: 'v' },
    { html: '&#119;', symbol: 'w' },
    { html: '&#120;', symbol: 'x' },
    { html: '&#121;', symbol: 'y' },
    { html: '&#122;', symbol: 'z' },
    { html: '&#123;', symbol: '{' },
    { html: '&#124;', symbol: '|' },
    { html: '&#125;', symbol: '}' },
    { html: '&#126;', symbol: '~' },
    { html: '&#127;', symbol: '' },
    { html: '&#128;', symbol: 'Ç' },
    { html: '&#129;', symbol: 'ü' },
    { html: '&#130;', symbol: 'é' },
    { html: '&#131;', symbol: 'â' },
    { html: '&#132;', symbol: 'ä' },
    { html: '&#133;', symbol: 'à' },
    { html: '&#134;', symbol: 'å' },
    { html: '&#135;', symbol: 'ç' },
    { html: '&#136;', symbol: 'ê' },
    { html: '&#137;', symbol: 'ë' },
    { html: '&#138;', symbol: 'è' },
    { html: '&#139;', symbol: 'ï' },
    { html: '&#140;', symbol: 'î' },
    { html: '&#141;', symbol: 'ì' },
    { html: '&#142;', symbol: 'Ä' },
    { html: '&#143;', symbol: 'Å' },
    { html: '&#144;', symbol: 'É' },
    { html: '&#145;', symbol: 'æ' },
    { html: '&#146;', symbol: 'Æ' },
    { html: '&#147;', symbol: 'ô' },
    { html: '&#148;', symbol: 'ö' },
    { html: '&#149;', symbol: 'ò' },
    { html: '&#150;', symbol: 'û' },
    { html: '&#151;', symbol: 'ù' },
    { html: '&#152;', symbol: 'ÿ' },
    { html: '&#153;', symbol: 'Ö' },
    { html: '&#154;', symbol: 'Ü' },
    { html: '&#155;', symbol: 'ø' },
    { html: '&#156;', symbol: '£' },
    { html: '&#157;', symbol: 'Ø' },
    { html: '&#158;', symbol: '×' },
    { html: '&#159;', symbol: 'ƒ' },
    { html: '&#160;', symbol: 'á' },
    { html: '&#161;', symbol: 'í' },
    { html: '&#162;', symbol: 'ó' },
    { html: '&#163;', symbol: 'ú' },
    { html: '&#164;', symbol: 'ñ' },
    { html: '&#165;', symbol: 'Ñ' },
    { html: '&#166;', symbol: 'ª' },
    { html: '&#167;', symbol: 'º' },
    { html: '&#168;', symbol: '¿' },
    { html: '&#169;', symbol: '®' },
    { html: '&#170;', symbol: '¬' },
    { html: '&#171;', symbol: '½' },
    { html: '&#172;', symbol: '¼' },
    { html: '&#173;', symbol: '¡' },
    { html: '&#174;', symbol: '«' },
    { html: '&#175;', symbol: '»' },
    { html: '&#176;', symbol: '░' },
    { html: '&#177;', symbol: '▒' },
    { html: '&#178;', symbol: '▓' },
    { html: '&#179;', symbol: '│' },
    { html: '&#180;', symbol: '┤' },
    { html: '&#181;', symbol: 'Á' },
    { html: '&#182;', symbol: 'Â' },
    { html: '&#183;', symbol: 'À' },
    { html: '&#184;', symbol: '©' },
    { html: '&#185;', symbol: '╣' },
    { html: '&#186;', symbol: '║' },
    { html: '&#187;', symbol: '╗' },
    { html: '&#188;', symbol: '╝' },
    { html: '&#189;', symbol: '¢' },
    { html: '&#190;', symbol: '¥' },
    { html: '&#191;', symbol: '┐' },
    { html: '&#192;', symbol: '└' },
    { html: '&#193;', symbol: '┴' },
    { html: '&#194;', symbol: '┬' },
    { html: '&#195;', symbol: '├' },
    { html: '&#196;', symbol: '─' },
    { html: '&#197;', symbol: '┼' },
    { html: '&#198;', symbol: 'ã' },
    { html: '&#199;', symbol: 'Ã' },
    { html: '&#200;', symbol: '╚' },
    { html: '&#201;', symbol: '╔' },
    { html: '&#202;', symbol: '╩' },
    { html: '&#203;', symbol: '╦' },
    { html: '&#204;', symbol: '╠' },
    { html: '&#205;', symbol: '═' },
    { html: '&#206;', symbol: '╬' },
    { html: '&#207;', symbol: '¤' },
    { html: '&#208;', symbol: 'ð' },
    { html: '&#209;', symbol: 'Ð' },
    { html: '&#210;', symbol: 'Ê' },
    { html: '&#211;', symbol: 'Ë' },
    { html: '&#212;', symbol: 'È' },
    { html: '&#213;', symbol: 'ı' },
    { html: '&#214;', symbol: 'Í' },
    { html: '&#215;', symbol: 'Î' },
    { html: '&#216;', symbol: 'Ï' },
    { html: '&#217;', symbol: '┘' },
    { html: '&#218;', symbol: '┌' },
    { html: '&#219;', symbol: '█' },
    { html: '&#220;', symbol: '▄' },
    { html: '&#221;', symbol: '¦' },
    { html: '&#222;', symbol: 'Ì' },
    { html: '&#223;', symbol: '▀' },
    { html: '&#224;', symbol: 'Ó' },
    { html: '&#225;', symbol: 'ß' },
    { html: '&#226;', symbol: 'Ô' },
    { html: '&#227;', symbol: 'Ò' },
    { html: '&#228;', symbol: 'õ' },
    { html: '&#229;', symbol: 'Õ' },
    { html: '&#230;', symbol: 'µ' },
    { html: '&#231;', symbol: 'þ' },
    { html: '&#232;', symbol: 'Þ' },
    { html: '&#233;', symbol: 'Ú' },
    { html: '&#234;', symbol: 'Û' },
    { html: '&#235;', symbol: 'Ù' },
    { html: '&#236;', symbol: 'ý' },
    { html: '&#237;', symbol: 'Ý' },
    { html: '&#238;', symbol: '¯' },
    { html: '&#239;', symbol: '´' },
    { html: '&#240;', symbol: '≡' },
    { html: '&#241;', symbol: '±' },
    { html: '&#242;', symbol: '‗' },
    { html: '&#243;', symbol: '¾' },
    { html: '&#244;', symbol: '¶' },
    { html: '&#245;', symbol: '§' },
    { html: '&#246;', symbol: '÷' },
    { html: '&#247;', symbol: '¸' },
    { html: '&#248;', symbol: '°' },
    { html: '&#249;', symbol: '¨' },
    { html: '&#250;', symbol: '·' },
    { html: '&#251;', symbol: '¹' },
    { html: '&#252;', symbol: '³' },
    { html: '&#253;', symbol: '²' },
    { html: '&#254;', symbol: '■' },
    { html: '&#255;', symbol: ' ' }
];

// Hexadecimal NCR
// Numeric character reference (NCR) en formato hexadecimal
const htmlEntityList_NCR_Hexadecimal = [
    { html: '&#x0026;', symbol: '&' },
    { html: '&#x003C;', symbol: '<' },
    { html: '&#x003E;', symbol: '>' },
    { html: '&#x0022;', symbol: '"' },
    { html: '&#x0027;', symbol: "'" }
];

// Named entity
// Named character reference (NCR) o entidad nombrada
const htmlEntityList_NCR_Named = [
    //-------------------------------------
    // - https://www.compart.com/en/unicode/U+0026
    // - HTML Entity
    { html: '&amp;', symbol: '&' },
    { html: '&lt;', symbol: '<' },
    { html: '&gt;', symbol: '>' },
    { html: '&quot;', symbol: '"' },
    { html: '&apos;', symbol: "'" }
];
