import {
    GoAlert,
    GoAlertFill,
    GoArchive,
    GoArrowBoth,
    GoArrowDown,
    GoArrowDownLeft,
    GoArrowDownRight,
    GoArrowLeft,
    GoArrowRight,
    GoArrowSwitch,
    GoArrowUp,
    GoArrowUpLeft,
    GoArrowUpRight,
    GoBell,
    GoBellFill,
    GoBellSlash,
    GoBlocked,
    GoBold,
    GoBook,
    GoBookmark,
    GoBookmarkFill,
    GoBookmarkSlash,
    GoBookmarkSlashFill,
    GoBriefcase,
    GoBroadcast,
    GoBrowser,
    GoBug,
    GoCalendar,
    GoCheck,
    GoCheckCircle,
    GoCheckCircleFill,
    GoChecklist,
    GoChevronDown,
    GoChevronLeft,
    GoChevronRight,
    GoChevronUp,
    GoCircle,
    GoCircleSlash,
    GoClock,
    GoCode,
    GoCodeOfConduct,
    GoCodeReview,
    GoCodeSquare,
    GoCodescan,
    GoCodescanCheckmark,
    GoComment,
    GoCopilot,
    GoCopy,
    GoCreditCard,
    GoDash,
    GoDatabase,
    GoDiamond,
    GoDiff,
    GoDot,
    GoDotFill,
    GoDownload,
    GoDuplicate,
    GoEye,
    GoEyeClosed,
    GoFile,
    GoFileBinary,
    GoFileCode,
    GoFileDirectory,
    GoFileDirectoryFill,
    GoFileMedia,
    GoFileSubmodule,
    GoFileSymlinkFile,
    GoFileZip,
    GoFilter,
    GoFlame,
    GoFold,
    GoFoldDown,
    GoFoldUp,
    GoGear,
    GoGift,
    GoGitBranch,
    GoGitCommit,
    GoGitCompare,
    GoGitMerge,
    GoGitPullRequest,
    GoGitPullRequestClosed,
    GoGitPullRequestDraft,
    GoGlobe,
    GoGrabber,
    GoGraph,
    GoHash,
    GoHeart,
    GoHeartFill,
    GoHistory,
    GoHome,
    GoHomeFill,
    GoHorizontalRule,
    GoHourglass,
    GoHubot,
    GoImage,
    GoInbox,
    GoInfinity,
    GoInfo,
    GoIssueClosed,
    GoIssueDraft,
    GoIssueOpened,
    GoIssueReopened,
    GoIssueTrackedBy,
    GoItalic,
    GoKebabHorizontal,
    GoKey,
    GoLaw,
    GoLightBulb,
    GoLink,
    GoLinkExternal,
    GoListOrdered,
    GoListUnordered,
    GoLocation,
    GoLock,
    GoLog,
    GoMail,
    GoMention,
    GoMilestone,
    GoMirror,
    GoMoon,
    GoMortarBoard,
    GoMoveToBottom,
    GoMoveToEnd,
    GoMoveToStart,
    GoMoveToTop,
    GoMute,
    GoNoEntry,
    GoNorthStar,
    GoNote,
    GoNumber,
    GoOrganization,
    GoPackage,
    GoPaperAirplane,
    GoPaperclip,
    GoPasskeyFill,
    GoPaste,
    GoPencil,
    GoPeople,
    GoPerson,
    GoPersonAdd,
    GoPersonFill,
    GoPin,
    GoPlay,
    GoPlug,
    GoPlus,
    GoPlusCircle,
    GoProject,
    GoProjectSymlink,
    GoProjectTemplate,
    GoPulse,
    GoQuestion,
    GoQuote,
    GoRead,
    GoRelFilePath,
    GoReply,
    GoReport,
    GoRocket,
    GoRows,
    GoScreenFull,
    GoScreenNormal,
    GoSearch,
    GoShare,
    GoShareAndroid,
    GoShield,
    GoShieldCheck,
    GoShieldLock,
    GoShieldSlash,
    GoShieldX,
    GoSidebarCollapse,
    GoSidebarExpand,
    GoSignIn,
    GoSignOut,
    GoSingleSelect,
    GoSkip,
    GoSmiley,
    GoSquare,
    GoSquareFill,
    GoSquirrel,
    GoStack,
    GoStar,
    GoStarFill,
    GoStop,
    GoStrikethrough,
    GoSun,
    GoSync,
    GoTab,
    GoTable,
    GoTag,
    GoTasklist,
    GoTelescope,
    GoTerminal,
    GoThumbsdown,
    GoThumbsup,
    GoTools,
    GoTrash,
    GoTriangleDown,
    GoTriangleLeft,
    GoTriangleRight,
    GoTriangleUp,
    GoUnfold,
    GoUnlink,
    GoUnlock,
    GoUnmute,
    GoUnread,
    GoUnverified,
    GoUpload,
    GoVerified,
    GoVersions,
    GoVideo,
    GoWorkflow,
    GoX,
    GoXCircle,
    GoXCircleFill
} from 'react-icons/go';

export const IconTypeGitHub = {
    Alert: GoAlert,
    AlertFill: GoAlertFill,
    Archive: GoArchive,
    ArrowBoth: GoArrowBoth,
    ArrowDown: GoArrowDown,
    ArrowDownLeft: GoArrowDownLeft,
    ArrowDownRight: GoArrowDownRight,
    ArrowLeft: GoArrowLeft,
    ArrowRight: GoArrowRight,
    ArrowSwitch: GoArrowSwitch,
    ArrowUp: GoArrowUp,
    ArrowUpLeft: GoArrowUpLeft,
    ArrowUpRight: GoArrowUpRight,
    Bell: GoBell,
    BellFill: GoBellFill,
    BellSlash: GoBellSlash,
    Blocked: GoBlocked,
    Bold: GoBold,
    Book: GoBook,
    Bookmark: GoBookmark,
    BookmarkFill: GoBookmarkFill,
    BookmarkSlash: GoBookmarkSlash,
    BookmarkSlashFill: GoBookmarkSlashFill,
    Briefcase: GoBriefcase,
    Broadcast: GoBroadcast,
    Browser: GoBrowser,
    Bug: GoBug,
    Calendar: GoCalendar,
    Check: GoCheck,
    CheckCircle: GoCheckCircle,
    CheckCircleFill: GoCheckCircleFill,
    Checklist: GoChecklist,
    ChevronDown: GoChevronDown,
    ChevronLeft: GoChevronLeft,
    ChevronRight: GoChevronRight,
    ChevronUp: GoChevronUp,
    Circle: GoCircle,
    CircleSlash: GoCircleSlash,
    Code: GoCode,
    CodeOfConduct: GoCodeOfConduct,
    CodeReview: GoCodeReview,
    CodeSquare: GoCodeSquare,
    Codescan: GoCodescan,
    CodescanCheckmark: GoCodescanCheckmark,
    Copy: GoCopy,
    Comment: GoComment,
    Copilot: GoCopilot,
    Clock: GoClock,
    CreditCard: GoCreditCard,
    Dash: GoDash,
    Database: GoDatabase,
    Diamond: GoDiamond,
    Diff: GoDiff,
    Dot: GoDot,
    DotFill: GoDotFill,
    Download: GoDownload,
    Duplicate: GoDuplicate,
    Eye: GoEye,
    EyeClosed: GoEyeClosed,
    File: GoFile,
    FileBinary: GoFileBinary,
    FileCode: GoFileCode,
    FileDirectory: GoFileDirectory,
    FileDirectoryFill: GoFileDirectoryFill,
    FileMedia: GoFileMedia,
    FileSubmodule: GoFileSubmodule,
    FileSymlinkFile: GoFileSymlinkFile,
    FileZip: GoFileZip,
    Filter: GoFilter,
    Flame: GoFlame,
    Fold: GoFold,
    FoldDown: GoFoldDown,
    FoldUp: GoFoldUp,
    Gear: GoGear,
    Gift: GoGift,
    GitBranch: GoGitBranch,
    GitCommit: GoGitCommit,
    GitCompare: GoGitCompare,
    GitMerge: GoGitMerge,
    GitPullRequest: GoGitPullRequest,
    GitPullRequestClosed: GoGitPullRequestClosed,
    GitPullRequestDraft: GoGitPullRequestDraft,
    Globe: GoGlobe,
    Grabber: GoGrabber,
    Graph: GoGraph,
    Hash: GoHash,
    Heart: GoHeart,
    HeartFill: GoHeartFill,
    History: GoHistory,
    Home: GoHome,
    HomeFill: GoHomeFill,
    HorizontalRule: GoHorizontalRule,
    Hourglass: GoHourglass,
    Hubot: GoHubot,
    Image: GoImage,
    Inbox: GoInbox,
    Infinity: GoInfinity,
    Info: GoInfo,
    IssueClosed: GoIssueClosed,
    IssueDraft: GoIssueDraft,
    IssueOpened: GoIssueOpened,
    IssueReopened: GoIssueReopened,
    IssueTrackedBy: GoIssueTrackedBy,
    Italic: GoItalic,
    KebabHorizontal: GoKebabHorizontal,
    Key: GoKey,
    Law: GoLaw,
    LightBulb: GoLightBulb,
    Link: GoLink,
    LinkExternal: GoLinkExternal,
    ListOrdered: GoListOrdered,
    ListUnordered: GoListUnordered,
    Location: GoLocation,
    Lock: GoLock,
    Log: GoLog,
    Mail: GoMail,
    Mention: GoMention,
    Milestone: GoMilestone,
    Mirror: GoMirror,
    Moon: GoMoon,
    MortarBoard: GoMortarBoard,
    MoveToBottom: GoMoveToBottom,
    MoveToEnd: GoMoveToEnd,
    MoveToStart: GoMoveToStart,
    MoveToTop: GoMoveToTop,
    Mute: GoMute,
    NoEntry: GoNoEntry,
    NorthStar: GoNorthStar,
    Note: GoNote,
    Number: GoNumber,
    Organization: GoOrganization,
    Package: GoPackage,
    PaperAirplane: GoPaperAirplane,
    Paperclip: GoPaperclip,
    Paste: GoPaste,
    PasskeyFill: GoPasskeyFill,
    Pencil: GoPencil,
    People: GoPeople,
    Person: GoPerson,
    PersonAdd: GoPersonAdd,
    PersonFill: GoPersonFill,
    Pin: GoPin,
    Play: GoPlay,
    Plug: GoPlug,
    Plus: GoPlus,
    PlusCircle: GoPlusCircle,
    Project: GoProject,
    ProjectSymlink: GoProjectSymlink,
    ProjectTemplate: GoProjectTemplate,
    Pulse: GoPulse,
    Question: GoQuestion,
    Quote: GoQuote,
    Read: GoRead,
    RelFilePath: GoRelFilePath,
    Reply: GoReply,
    Report: GoReport,
    Rocket: GoRocket,
    Rows: GoRows,
    ScreenFull: GoScreenFull,
    ScreenNormal: GoScreenNormal,
    Search: GoSearch,
    Share: GoShare,
    ShareAndroid: GoShareAndroid,
    Shield: GoShield,
    ShieldCheck: GoShieldCheck,
    ShieldLock: GoShieldLock,
    ShieldSlash: GoShieldSlash,
    ShieldX: GoShieldX,
    SidebarCollapse: GoSidebarCollapse,
    SidebarExpand: GoSidebarExpand,
    SignIn: GoSignIn,
    SignOut: GoSignOut,
    SingleSelect: GoSingleSelect,
    Skip: GoSkip,
    Smiley: GoSmiley,
    Square: GoSquare,
    SquareFill: GoSquareFill,
    Squirrel: GoSquirrel,
    Stack: GoStack,
    Star: GoStar,
    StarFill: GoStarFill,
    Stop: GoStop,
    Strikethrough: GoStrikethrough,
    Sun: GoSun,
    Sync: GoSync,
    Tab: GoTab,
    Table: GoTable,
    Tag: GoTag,
    Tasklist: GoTasklist,
    Telescope: GoTelescope,
    Terminal: GoTerminal,
    Thumbsdown: GoThumbsdown,
    Thumbsup: GoThumbsup,
    Tools: GoTools,
    Trash: GoTrash,
    TriangleDown: GoTriangleDown,
    TriangleLeft: GoTriangleLeft,
    TriangleRight: GoTriangleRight,
    TriangleUp: GoTriangleUp,
    Unfold: GoUnfold,
    Unlink: GoUnlink,
    Unlock: GoUnlock,
    Unmute: GoUnmute,
    Unread: GoUnread,
    Unverified: GoUnverified,
    Upload: GoUpload,
    Verified: GoVerified,
    Versions: GoVersions,
    Video: GoVideo,
    Workflow: GoWorkflow,
    X: GoX,
    XCircle: GoXCircle,
    XCircleFill: GoXCircleFill
};

export type typeGitHubIcons = keyof typeof IconTypeGitHub;
